python Test_API.py
--src_image
/Disk1/Projects/Blend/material/plane.jpeg
--dst_image
/Disk1/Projects/Blend/material/sky.jpeg
--mask_image
/Disk1/Projects/Blend/material/plane_mask.png
--blended_image
GP_results/res_ZRS_GP_sea.png
--color_weight
5e-8
--invert_mask
0
--inpaint_bg
0

--src_image
/Disk1/XR/ZRS/src.jpg
--dst_image
/Disk1/XR/ZRS/dst.png
--mask_image
/Disk1/XR/ZRS/mask.png
--blended_image
result_ZRS.png
--color_weight
6e-6
--invert_mask
1
--inpaint_bg
0

--src_image
/Disk1/Projects/Blend/material/sea_src.jpg
--dst_image
/Disk1/Projects/Blend/material/sea_dst.jpg
--mask_image
/Disk1/Projects/Blend/material/sea_mask.png
--blended_image
res_ZRS_GP_sea.png
--color_weight
8e-2
--invert_mask
0
--inpaint_bg
0